In [1]:
import numpy as np
import scipy.linalg as la

In [312]:
def house(A):
    """ Returns an upper triangular matrix R and lower triangular matrix W. """
    m,n = A.shape
    v = [] # Stores reflectors to make W
    for k in range(n):
        x = A[k:m,k]
        e1 = np.zeros(len(x))
        e1[0] = 1
        v_k = np.sign(x[0])*la.norm(x,ord=2)*e1+x
        v_k = v_k/la.norm(v_k,ord=2)
        v.append(v_k)
        A[k:m,k:n] = A[k:m,k:n]-2*np.outer(v_k,(v_k@A[k:m,k:n]))
        
    # Make W
    W = np.zeros((m,n))    
    for i,col in enumerate(v):
        W[i:,i] = col
        
    return A, W
    

In [313]:
A = np.random.randn(4,4)
R, W = house(A)
print("R Matrix:\n{}".format(R))
print("\n")
print("W Matrix:\n{}".format(W))

R Matrix:
[[-2.43826399e+00  1.30346214e+00 -2.69546878e-01  4.37178733e-01]
 [ 0.00000000e+00  1.53476187e+00  6.85757399e-01  2.38698616e+00]
 [ 0.00000000e+00  0.00000000e+00  1.55933095e+00 -6.64519111e-01]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16  3.26693868e-01]]


W Matrix:
[[ 0.96954589  0.          0.          0.        ]
 [-0.24438186 -0.86740739  0.          0.        ]
 [-0.01352309  0.13176351 -0.90161539  0.        ]
 [ 0.00868297  0.47983622 -0.43253865 -1.        ]]


In [317]:
def formQ(W):
    """ Given a W, forms the unitary matrix Q. """
    
    m, n = W.shape
    Q_s = []
    for j in range(n):
        v = W[:,j]
        Q_s.append(np.eye(m)-2*np.outer(v,v)) # Q = I-2vv.T
        
    Q = Q_s[0].copy()
    for q_ in Q_s[1:]:
        Q = Q@q_ # Formula 10.7
    
    return Q

In [318]:
Q = formQ(W)

In [319]:
# Check it's unitary
np.allclose(np.eye(W.shape[0]), Q@Q.T)

True